// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"code.cloudfoundry.org/routing-api/db"
	"code.cloudfoundry.org/routing-api/migration"
)

type FakeMigration struct {
	RunMigrationStub        func(database db.DB) error
	runMigrationMutex       sync.RWMutex
	runMigrationArgsForCall []struct {
		database db.DB
	}
	runMigrationReturns struct {
		result1 error
	}
	VersionStub        func() int
	versionMutex       sync.RWMutex
	versionArgsForCall []struct{}
	versionReturns     struct {
		result1 int
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMigration) RunMigration(database db.DB) error {
	fake.runMigrationMutex.Lock()
	fake.runMigrationArgsForCall = append(fake.runMigrationArgsForCall, struct {
		database db.DB
	}{database})
	fake.recordInvocation("RunMigration", []interface{}{database})
	fake.runMigrationMutex.Unlock()
	if fake.RunMigrationStub != nil {
		return fake.RunMigrationStub(database)
	} else {
		return fake.runMigrationReturns.result1
	}
}

func (fake *FakeMigration) RunMigrationCallCount() int {
	fake.runMigrationMutex.RLock()
	defer fake.runMigrationMutex.RUnlock()
	return len(fake.runMigrationArgsForCall)
}

func (fake *FakeMigration) RunMigrationArgsForCall(i int) db.DB {
	fake.runMigrationMutex.RLock()
	defer fake.runMigrationMutex.RUnlock()
	return fake.runMigrationArgsForCall[i].database
}

func (fake *FakeMigration) RunMigrationReturns(result1 error) {
	fake.RunMigrationStub = nil
	fake.runMigrationReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMigration) Version() int {
	fake.versionMutex.Lock()
	fake.versionArgsForCall = append(fake.versionArgsForCall, struct{}{})
	fake.recordInvocation("Version", []interface{}{})
	fake.versionMutex.Unlock()
	if fake.VersionStub != nil {
		return fake.VersionStub()
	} else {
		return fake.versionReturns.result1
	}
}

func (fake *FakeMigration) VersionCallCount() int {
	fake.versionMutex.RLock()
	defer fake.versionMutex.RUnlock()
	return len(fake.versionArgsForCall)
}

func (fake *FakeMigration) VersionReturns(result1 int) {
	fake.VersionStub = nil
	fake.versionReturns = struct {
		result1 int
	}{result1}
}

func (fake *FakeMigration) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMigrationMutex.RLock()
	defer fake.runMigrationMutex.RUnlock()
	fake.versionMutex.RLock()
	defer fake.versionMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeMigration) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ migration.Migration = new(FakeMigration)
